"""add room config fields to chat_sessions

Revision ID: 58d909b82a5f
Revises: e4cadf77d55e
Create Date: 2025-07-25 16:34:51.741133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d909b82a5f'
down_revision: Union[str, Sequence[str], None] = 'e4cadf77d55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('vote_type', sa.String(length=20), nullable=True))
    op.add_column('chat_sessions', sa.Column('speaker_order', sa.String(length=20), nullable=True))
    op.add_column('chat_sessions', sa.Column('max_rounds', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('hard_mode', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('vote_timeout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'vote_timeout')
    op.drop_column('chat_sessions', 'hard_mode')
    op.drop_column('chat_sessions', 'max_rounds')
    op.drop_column('chat_sessions', 'speaker_order')
    op.drop_column('chat_sessions', 'vote_type')
    # ### end Alembic commands ###
