"""Initial migration

Revision ID: 6c456c92393e
Revises: 
Create Date: 2025-07-21 16:13:30.035433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c456c92393e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name_ja', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=False),
    sa.Column('mode_id', sa.String(length=36), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'playing', 'finished', name='chat_session_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solo_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('target_emotion_id', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('ai_predicted_emotion_id', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('bonus_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ai_predicted_emotion_id'], ['emotion_types.id'], ),
    sa.ForeignKeyConstraint(['target_emotion_id'], ['emotion_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_session_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('emotion_id', sa.String(length=50), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotion_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('voter_session_id', sa.String(length=36), nullable=False),
    sa.Column('selected_emotion_id', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['selected_emotion_id'], ['emotion_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=True),
    sa.Column('solo_session_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['solo_session_id'], ['solo_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=True),
    sa.Column('solo_session_id', sa.String(length=36), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.Enum('listener', 'speaker', 'solo', name='score_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['solo_session_id'], ['solo_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('recordings')
    op.drop_table('emotion_votes')
    op.drop_table('rounds')
    op.drop_table('room_participants')
    op.drop_table('solo_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('modes')
    op.drop_table('emotion_types')
    # ### end Alembic commands ###
