"""add host_token to chat_sessions

Revision ID: e4cadf77d55e
Revises: f98096dfa604
Create Date: 2025-07-25 16:25:04.433872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cadf77d55e'
down_revision: Union[str, Sequence[str], None] = 'f98096dfa604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'current_speaker_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    
    # Add host_token column
    op.add_column('chat_sessions', sa.Column('host_token', sa.String(36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove host_token column
    op.drop_column('chat_sessions', 'host_token')
    
    op.alter_column('chat_sessions', 'current_speaker_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    # ### end Alembic commands ###
