"""add_current_speaker_index_to_chat_sessions

Revision ID: f98096dfa604
Revises: 6c456c92393e
Create Date: 2025-07-25 15:53:26.224529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98096dfa604'
down_revision: Union[str, Sequence[str], None] = '6c456c92393e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('current_speaker_index', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'current_speaker_index')
    # ### end Alembic commands ###
